spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: notifications-microservice
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT}

app:
  internal:
    api-key: ${INTERNAL_API_KEY:ta-internal-api-key}
  confirmation-code:
    ttl-minutes: ${CONFIRMATION_CODE_TTL_MINUTES:5}
  mail:
    from: ${MAIL_FROM:no-reply@yandex.ru}
    from-name: ${MAIL_FROM_NAME:Учебные ассистенты ФКН}
  rabbitmq:
    application-status:
      exchange: ${APPLICATION_STATUS_EVENTS_EXCHANGE:ta.application-events}
      queue: ${APPLICATION_STATUS_EVENTS_QUEUE:notifications.application-status-updated}
      routing-key: ${APPLICATION_STATUS_EVENTS_ROUTING_KEY:application.status.updated}
    confirmation-code:
      exchange: ${STUDENT_CONFIRMATION_CODE_EVENTS_EXCHANGE:ta.user-events}
      queue: ${STUDENT_CONFIRMATION_CODE_EVENTS_QUEUE:notifications.student-confirmation-code-generated}
      routing-key: ${STUDENT_CONFIRMATION_CODE_EVENTS_ROUTING_KEY:student.confirmation-code.generated}
    employee-confirmation-code:
      exchange: ${EMPLOYEE_CONFIRMATION_CODE_EVENTS_EXCHANGE:ta.user-events}
      queue: ${EMPLOYEE_CONFIRMATION_CODE_EVENTS_QUEUE:notifications.employee-confirmation-code-generated}
      routing-key: ${EMPLOYEE_CONFIRMATION_CODE_EVENTS_ROUTING_KEY:employee.confirmation-code.generated}

clients:
  users:
    base-url: ${USERS_SERVICE_BASE_URL:http://users-microservice:8089/api/v1}
  disciplines:
    base-url: ${DISCIPLINES_SERVICE_BASE_URL:http://disciplines-microservice:8084/api/v1}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
